dist: trusty

notifications:
  slack: omni-digital:8GlIRcLNKvu8SAP7LWH4qd3e

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - tox
